
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


    /**
     * Version 1.0.1.2
     * @author Simon Hornestedt och Mattias Nordberg
     */
public class GUI extends javax.swing.JFrame {
    ImageIcon img;
    InventoryTableModel InventoryTable;
    Model mod;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        mod = new Model();
        img = new ImageIcon("../Projektuppgiften/icon.PNG");
        InventoryTable = new InventoryTableModel();
        this.setIconImage(img.getImage());
        jTableInv.setModel(InventoryTable);  
        setGearVisibility(false);
        enableButtons(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlMarketplace = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tabMarket = new javax.swing.JTabbedPane();
        pnl2HandedMarket = new javax.swing.JPanel();
        cmb2Handed = new javax.swing.JComboBox();
        lbl2Handed = new javax.swing.JLabel();
        btnBuy2Handed = new javax.swing.JButton();
        pnl1handedMarket = new javax.swing.JPanel();
        cmb1Handed = new javax.swing.JComboBox();
        lbl1handed = new javax.swing.JLabel();
        btnBuy1Handed = new javax.swing.JButton();
        pnlShieldMarket = new javax.swing.JPanel();
        cmbShield = new javax.swing.JComboBox();
        lblShield = new javax.swing.JLabel();
        btnBuyShield = new javax.swing.JButton();
        pnlArmorMarket = new javax.swing.JPanel();
        cmbCloth = new javax.swing.JComboBox();
        cmbLeather = new javax.swing.JComboBox();
        cmbMetal = new javax.swing.JComboBox();
        lblMarketCloth = new javax.swing.JLabel();
        lblLeather = new javax.swing.JLabel();
        lblMetal = new javax.swing.JLabel();
        cmbRing = new javax.swing.JComboBox();
        lblRings = new javax.swing.JLabel();
        btnCloth = new javax.swing.JButton();
        btnLeather = new javax.swing.JButton();
        btnMetal = new javax.swing.JButton();
        btnRing = new javax.swing.JButton();
        pnlArena = new javax.swing.JPanel();
        pnlArenaOpt = new javax.swing.JPanel();
        lblMonster = new javax.swing.JLabel();
        cmbMonster = new javax.swing.JComboBox();
        btnMonsterInfo = new javax.swing.JButton();
        btnEnterArena = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaArena = new javax.swing.JTextArea();
        pnlHero = new javax.swing.JPanel();
        lblAgi = new javax.swing.JLabel();
        lblStr = new javax.swing.JLabel();
        lblSpd = new javax.swing.JLabel();
        lblTgh = new javax.swing.JLabel();
        lblWepSkills = new javax.swing.JLabel();
        lblStats = new javax.swing.JLabel();
        lblOneStats = new javax.swing.JLabel();
        lblTwoStats = new javax.swing.JLabel();
        lblHackStats = new javax.swing.JLabel();
        txfAgi = new javax.swing.JTextField();
        txfStr = new javax.swing.JTextField();
        txfSpd = new javax.swing.JTextField();
        txfTgh = new javax.swing.JTextField();
        txf2h = new javax.swing.JTextField();
        txf1h = new javax.swing.JTextField();
        txfShield = new javax.swing.JTextField();
        txfPoints = new javax.swing.JTextField();
        pnlGear = new javax.swing.JPanel();
        lblChest = new javax.swing.JLabel();
        lblHelm = new javax.swing.JLabel();
        lblArm = new javax.swing.JLabel();
        lblLegs = new javax.swing.JLabel();
        lblFeet = new javax.swing.JLabel();
        lblRing = new javax.swing.JLabel();
        lblTwoHanded = new javax.swing.JLabel();
        lblOneHanded = new javax.swing.JLabel();
        lblGearShield = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInv = new javax.swing.JTable();
        btnEquip = new javax.swing.JButton();
        btnSetStats = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        pnlCharacter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblGladName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLvl = new javax.swing.JLabel();
        lblExp = new javax.swing.JLabel();
        lblHp = new javax.swing.JLabel();
        lblGold = new javax.swing.JLabel();
        txfLvl = new javax.swing.JTextField();
        txfExp = new javax.swing.JTextField();
        txfHp = new javax.swing.JTextField();
        txfGold = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemOpen = new javax.swing.JMenuItem();
        menuItemNew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();
        menuItemHelp = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab1", jPanel6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gladiator III");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Marketplace.PNG"))); // NOI18N

        cmb2Handed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Sword", "Basic Mace", "Basic Spear", "Frostmourne", "Sulfuras", "Dragon Glavie" }));
        cmb2Handed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb2HandedActionPerformed(evt);
            }
        });

        lbl2Handed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl2Handed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2HandedMouseClicked(evt);
            }
        });

        btnBuy2Handed.setText("Buy 2-Handed Weapon");
        btnBuy2Handed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuy2HandedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl2HandedMarketLayout = new javax.swing.GroupLayout(pnl2HandedMarket);
        pnl2HandedMarket.setLayout(pnl2HandedMarketLayout);
        pnl2HandedMarketLayout.setHorizontalGroup(
            pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2HandedMarketLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuy2Handed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb2Handed, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(lbl2Handed, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        pnl2HandedMarketLayout.setVerticalGroup(
            pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2HandedMarketLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2HandedMarketLayout.createSequentialGroup()
                        .addComponent(cmb2Handed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btnBuy2Handed)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2HandedMarketLayout.createSequentialGroup()
                        .addComponent(lbl2Handed, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        tabMarket.addTab("2-Handed Weapons", pnl2HandedMarket);

        cmb1Handed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Axe", "Small Basic Mace", "Basic Dagger", "Shadowmourne", "Morningstar of Agmar", "Fangs of the Father" }));
        cmb1Handed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1HandedActionPerformed(evt);
            }
        });

        lbl1handed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl1handed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1handedMouseClicked(evt);
            }
        });

        btnBuy1Handed.setText("Buy 1-Handed Weapon");
        btnBuy1Handed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuy1HandedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl1handedMarketLayout = new javax.swing.GroupLayout(pnl1handedMarket);
        pnl1handedMarket.setLayout(pnl1handedMarketLayout);
        pnl1handedMarketLayout.setHorizontalGroup(
            pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1handedMarketLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuy1Handed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb1Handed, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(lbl1handed, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        pnl1handedMarketLayout.setVerticalGroup(
            pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1handedMarketLayout.createSequentialGroup()
                .addGroup(pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1handedMarketLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(cmb1Handed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnBuy1Handed))
                    .addGroup(pnl1handedMarketLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbl1handed, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tabMarket.addTab("1-Handed Weapons", pnl1handedMarket);

        cmbShield.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Round Shield", "Roman Shield" }));
        cmbShield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbShieldActionPerformed(evt);
            }
        });

        lblShield.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShieldMouseClicked(evt);
            }
        });

        btnBuyShield.setText("Buy Shield");
        btnBuyShield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyShieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlShieldMarketLayout = new javax.swing.GroupLayout(pnlShieldMarket);
        pnlShieldMarket.setLayout(pnlShieldMarketLayout);
        pnlShieldMarketLayout.setHorizontalGroup(
            pnlShieldMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShieldMarketLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(pnlShieldMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbShield, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuyShield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(lblShield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        pnlShieldMarketLayout.setVerticalGroup(
            pnlShieldMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShieldMarketLayout.createSequentialGroup()
                .addGroup(pnlShieldMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlShieldMarketLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblShield, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlShieldMarketLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(cmbShield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuyShield)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabMarket.addTab("Shields", pnlShieldMarket);

        cmbCloth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Helm", "Upperbody", "Arms", "Lowerbody", "Feet" }));

        cmbLeather.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Helm", "Upperbody", "Arms", "Lowerbody", "Feet" }));

        cmbMetal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Helm", "Upperbody", "Arms", "Lowerbody", "Feet" }));

        lblMarketCloth.setText("Cloth Armor");
        lblMarketCloth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMarketCloth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMarketClothMouseClicked(evt);
            }
        });

        lblLeather.setText("Leather Armor");
        lblLeather.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLeather.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLeatherMouseClicked(evt);
            }
        });

        lblMetal.setText("Metal Armor");
        lblMetal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMetal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMetalMouseClicked(evt);
            }
        });

        cmbRing.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Band of Pain", "Signet of Speed", "Legendary Amulet" }));
        cmbRing.setSelectedIndex(2);

        lblRings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRings.setText("Rings");
        lblRings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRingsMouseClicked(evt);
            }
        });

        btnCloth.setText("Buy Cloth");
        btnCloth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClothActionPerformed(evt);
            }
        });

        btnLeather.setText("Buy Leather");
        btnLeather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeatherActionPerformed(evt);
            }
        });

        btnMetal.setText("Buy Metal");
        btnMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetalActionPerformed(evt);
            }
        });

        btnRing.setText("Buy Ring");
        btnRing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlArmorMarketLayout = new javax.swing.GroupLayout(pnlArmorMarket);
        pnlArmorMarket.setLayout(pnlArmorMarketLayout);
        pnlArmorMarketLayout.setHorizontalGroup(
            pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArmorMarketLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlArmorMarketLayout.createSequentialGroup()
                            .addComponent(cmbCloth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArmorMarketLayout.createSequentialGroup()
                            .addComponent(btnCloth)
                            .addGap(57, 57, 57)))
                    .addGroup(pnlArmorMarketLayout.createSequentialGroup()
                        .addComponent(lblMarketCloth)
                        .addGap(79, 79, 79)))
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeather)
                    .addComponent(btnLeather)
                    .addComponent(cmbLeather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMetal)
                    .addComponent(lblMetal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbRing, 0, 123, Short.MAX_VALUE)
                        .addComponent(btnRing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblRings, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        pnlArmorMarketLayout.setVerticalGroup(
            pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArmorMarketLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCloth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLeather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarketCloth, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLeather, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMetal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRings, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCloth)
                    .addComponent(btnMetal)
                    .addComponent(btnLeather)
                    .addComponent(btnRing))
                .addGap(73, 73, 73))
        );

        tabMarket.addTab("Armor", pnlArmorMarket);

        javax.swing.GroupLayout pnlMarketplaceLayout = new javax.swing.GroupLayout(pnlMarketplace);
        pnlMarketplace.setLayout(pnlMarketplaceLayout);
        pnlMarketplaceLayout.setHorizontalGroup(
            pnlMarketplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarketplaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMarketplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabMarket)
                    .addGroup(pnlMarketplaceLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMarketplaceLayout.setVerticalGroup(
            pnlMarketplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarketplaceLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 324, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Marketplace", pnlMarketplace);

        lblMonster.setText("Monster:");

        cmbMonster.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Goblin", "Dwarf", "Troll", "Elemental", "Nerubian", "Giant", "Arthis the Lich Queen" }));

        btnMonsterInfo.setText("Info");
        btnMonsterInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonsterInfoActionPerformed(evt);
            }
        });

        btnEnterArena.setText("Enter the Arena");
        btnEnterArena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterArenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlArenaOptLayout = new javax.swing.GroupLayout(pnlArenaOpt);
        pnlArenaOpt.setLayout(pnlArenaOptLayout);
        pnlArenaOptLayout.setHorizontalGroup(
            pnlArenaOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArenaOptLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlArenaOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMonster)
                    .addComponent(cmbMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(pnlArenaOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEnterArena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMonsterInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(176, 176, 176))
        );
        pnlArenaOptLayout.setVerticalGroup(
            pnlArenaOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArenaOptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArenaOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonster)
                    .addComponent(btnMonsterInfo))
                .addGap(18, 18, 18)
                .addGroup(pnlArenaOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnterArena))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        txaArena.setEditable(false);
        txaArena.setColumns(20);
        txaArena.setLineWrap(true);
        txaArena.setRows(5);
        txaArena.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txaArena);

        javax.swing.GroupLayout pnlArenaLayout = new javax.swing.GroupLayout(pnlArena);
        pnlArena.setLayout(pnlArenaLayout);
        pnlArenaLayout.setHorizontalGroup(
            pnlArenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(pnlArenaOpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlArenaLayout.setVerticalGroup(
            pnlArenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArenaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlArenaOpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Arena", pnlArena);

        lblAgi.setText("Agility:");

        lblStr.setText("Strength:");

        lblSpd.setText("Speed: ");

        lblTgh.setText("Toughness: ");

        lblWepSkills.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblWepSkills.setText("Weapon Skills");

        lblStats.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStats.setText("Stats");

        lblOneStats.setText("1-Handed:");

        lblTwoStats.setText("2-Handed:");

        lblHackStats.setText("Shield:");

        txfAgi.setEditable(false);
        txfAgi.setFocusable(false);

        txfStr.setEditable(false);
        txfStr.setFocusable(false);

        txfSpd.setEditable(false);
        txfSpd.setFocusable(false);

        txfTgh.setEditable(false);
        txfTgh.setFocusable(false);

        txf2h.setEditable(false);
        txf2h.setFocusable(false);

        txf1h.setEditable(false);
        txf1h.setFocusable(false);

        txfShield.setEditable(false);
        txfShield.setFocusable(false);

        txfPoints.setEditable(false);
        txfPoints.setFocusable(false);

        pnlGear.setMinimumSize(new java.awt.Dimension(401, 449));

        lblChest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/breast.png"))); // NOI18N
        lblChest.setText("HARNESK");
        lblChest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblChest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChestMouseClicked(evt);
            }
        });

        lblHelm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/helm.png"))); // NOI18N
        lblHelm.setText(" HJÄLM");
        lblHelm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHelm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHelmMouseClicked(evt);
            }
        });

        lblArm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arm.png"))); // NOI18N
        lblArm.setText("ARM");
        lblArm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblArm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblArmMouseClicked(evt);
            }
        });

        lblLegs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legs.png"))); // NOI18N
        lblLegs.setText("BEN");
        lblLegs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLegs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLegsMouseClicked(evt);
            }
        });

        lblFeet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandal.png"))); // NOI18N
        lblFeet.setText("SKOR");
        lblFeet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFeet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFeetMouseClicked(evt);
            }
        });

        lblRing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ring.png"))); // NOI18N
        lblRing.setText("RING");
        lblRing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRingMouseClicked(evt);
            }
        });

        lblTwoHanded.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblTwoHanded.setText("2H EQUIPPED");
        lblTwoHanded.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTwoHanded.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTwoHandedMouseClicked(evt);
            }
        });

        lblOneHanded.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblOneHanded.setText("1H EQUIPPED");
        lblOneHanded.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOneHanded.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOneHandedMouseClicked(evt);
            }
        });

        lblGearShield.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblGearShield.setText("SHIELD EQUIPPED");
        lblGearShield.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGearShield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGearShieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlGearLayout = new javax.swing.GroupLayout(pnlGear);
        pnlGear.setLayout(pnlGearLayout);
        pnlGearLayout.setHorizontalGroup(
            pnlGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlGearLayout.createSequentialGroup()
                        .addComponent(lblOneHanded, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGearShield, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLegs, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChest, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlGearLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblFeet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRing, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(pnlGearLayout.createSequentialGroup()
                        .addComponent(lblTwoHanded, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addComponent(lblHelm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        pnlGearLayout.setVerticalGroup(
            pnlGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGearLayout.createSequentialGroup()
                .addGroup(pnlGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGearLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHelm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGearLayout.createSequentialGroup()
                                .addComponent(lblChest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLegs, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblFeet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlGearLayout.createSequentialGroup()
                                .addComponent(lblArm, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(lblRing, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlGearLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblTwoHanded, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOneHanded, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGearShield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jTableInv);

        btnEquip.setText("Equip");
        btnEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipActionPerformed(evt);
            }
        });

        btnSetStats.setText("Set Stats");
        btnSetStats.setEnabled(false);
        btnSetStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetStatsActionPerformed(evt);
            }
        });

        btnInfo.setText("Info");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeroLayout = new javax.swing.GroupLayout(pnlHero);
        pnlHero.setLayout(pnlHeroLayout);
        pnlHeroLayout.setHorizontalGroup(
            pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addComponent(pnlGear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblHackStats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txfShield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblTwoStats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txf2h, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblOneStats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txf1h, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblTgh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                                .addComponent(txfTgh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblWepSkills)
                                .addGap(0, 166, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeroLayout.createSequentialGroup()
                                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSpd)
                                    .addComponent(lblStr)
                                    .addComponent(lblAgi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfAgi)
                                    .addComponent(txfStr, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(txfSpd, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblStats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfPoints, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSetStats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeroLayout.createSequentialGroup()
                        .addComponent(btnEquip)
                        .addGap(18, 18, 18)
                        .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276)))
                .addContainerGap())
        );
        pnlHeroLayout.setVerticalGroup(
            pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeroLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEquip)
                            .addComponent(btnInfo))
                        .addGap(16, 16, 16)
                        .addComponent(pnlGear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStats)
                            .addComponent(btnSetStats))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAgi)
                            .addComponent(txfAgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStr)
                            .addComponent(txfStr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSpd)
                            .addComponent(txfSpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTgh)
                            .addComponent(txfTgh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblWepSkills)
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOneStats)
                            .addComponent(txf1h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTwoStats)
                            .addComponent(txf2h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHackStats)
                            .addComponent(txfShield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(txfPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTabbedPane1.addTab("Hero", pnlHero);

        pnlCharacter.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Character", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP)), "Character", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP))));
        pnlCharacter.setPreferredSize(new java.awt.Dimension(216, 782));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heroFace.png"))); // NOI18N
        jLabel1.setText("BILD");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblGladName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGladName.setText("Name:");

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLvl.setText("Level:");

        lblExp.setText("Exp:");

        lblHp.setText("HP:");

        lblGold.setText("Gold:");

        txfLvl.setEditable(false);
        txfLvl.setFocusable(false);

        txfExp.setEditable(false);
        txfExp.setFocusable(false);

        txfHp.setEditable(false);
        txfHp.setFocusable(false);

        txfGold.setEditable(false);
        txfGold.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLvl)
                    .addComponent(lblExp)
                    .addComponent(lblHp)
                    .addComponent(lblGold))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfLvl, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txfExp)
                    .addComponent(txfHp)
                    .addComponent(txfGold))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLvl)
                    .addComponent(txfLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExp)
                    .addComponent(txfExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHp)
                    .addComponent(txfHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGold)
                    .addComponent(txfGold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCharacterLayout = new javax.swing.GroupLayout(pnlCharacter);
        pnlCharacter.setLayout(pnlCharacterLayout);
        pnlCharacterLayout.setHorizontalGroup(
            pnlCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCharacterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCharacterLayout.createSequentialGroup()
                        .addComponent(lblGladName)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlCharacterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCharacterLayout.setVerticalGroup(
            pnlCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCharacterLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblGladName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        menuFile.setText("File");

        menuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSave.setText("Save");
        menuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuItemSave);

        menuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuItemOpen.setText("Open");
        menuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenActionPerformed(evt);
            }
        });
        menuFile.add(menuItemOpen);

        menuItemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuItemNew.setText("New");
        menuItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewActionPerformed(evt);
            }
        });
        menuFile.add(menuItemNew);
        menuFile.add(jSeparator1);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuItemExit.setText("Exit...");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        jMenuBar1.add(menuFile);

        jMenu2.setText("Help");

        menuItemAbout.setText("About");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemAbout);

        menuItemHelp.setText("Help");
        menuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHelpActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemHelp);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0)
                .addComponent(pnlCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pnlCharacter, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Sätter nödvändiga knappar synliga/osynliga
     * @param b boolean true för synlig false för osynlig
     */
    private void enableButtons(boolean b){
        menuItemSave.setEnabled(b);
        btnBuy1Handed.setEnabled(b);
        btnBuy2Handed.setEnabled(b);
        btnBuyShield.setEnabled(b);
        btnCloth.setEnabled(b);
        btnLeather.setEnabled(b);
        btnMetal.setEnabled(b);
        btnRing.setEnabled(b);
        btnEnterArena.setEnabled(b);
        btnMonsterInfo.setEnabled(b);
    }
    
    /**
     * Knappevent för helpknappen
     * @param evt Action event
     */
    private void menuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHelpActionPerformed
       JOptionPane.showMessageDialog(null, "r u a n0b?");
    }//GEN-LAST:event_menuItemHelpActionPerformed
    
    /**
     * Knappevent för cmb2handend
     * @param evt Action event
     */
    private void cmb2HandedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb2HandedActionPerformed
        switch(cmb2Handed.getSelectedIndex()){
            case 1: 
                lbl2Handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2hmace1.PNG")));
            break;
            case 2: 
                lbl2Handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spear1.PNG")));
            break;
            case 3: 
                lbl2Handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sword2.PNG")));
            break;    
            case 4: 
                lbl2Handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2hmace2.PNG")));
            break;    
            case 5: 
                lbl2Handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spear2.PNG")));
            break;
            default:
                lbl2Handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sword1.png")));
            break;
        }
    }//GEN-LAST:event_cmb2HandedActionPerformed
    
    /**
     * Knappevent för cmb1hand
     * @param evt Action event
     */
    private void cmb1HandedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1HandedActionPerformed
        switch(cmb1Handed.getSelectedIndex()){
            case 1: 
                lbl1handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1hmace1.png")));
            break;
            case 2: 
                lbl1handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dagger1.PNG")));
            break;
            case 3: 
                lbl1handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/axe2.PNG")));
            break;
            case 4: 
                lbl1handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1hmace2.PNG")));
            break;
            case 5: 
                lbl1handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dagger2.PNG")));
            break;
            default:
                lbl1handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/axe1.png")));
            break;
        }
    }//GEN-LAST:event_cmb1HandedActionPerformed
    
    /**
     * Knappevent för cmbShield
     * @param evt Action event
     */
    private void cmbShieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbShieldActionPerformed
        switch(cmbShield.getSelectedIndex()){
            case 1: 
                lblShield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/romersk.png")));
            break;
            default:
                lblShield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rundsköld.png")));
            break;
        }
    }//GEN-LAST:event_cmbShieldActionPerformed
    
    /**
     * Knappevent för exit knapp
     * @param evt Action event
     */
    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Do you really wish to exit the program?", "Exit?", JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION){
        System.exit(EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_menuItemExitActionPerformed
    
    /**
     * Knappevent för new knappen
     * @param evt Action event
     */
    private void menuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewActionPerformed
        String newHeroName = JOptionPane.showInputDialog(null,
                "Please choose a name for your gladiator:",
                "New gladiator:", 
                JOptionPane.PLAIN_MESSAGE);
        if(newHeroName != null){
            Player tmp = mod.createHero(newHeroName);
            this.updateHeroPnl(tmp);
            enableButtons(true);
        }        
    }//GEN-LAST:event_menuItemNewActionPerformed
    
    /**
     * Knappevent för Save knapp
     * @param evt Action event
     */
    private void menuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveActionPerformed
        mod.saveHero();
    }//GEN-LAST:event_menuItemSaveActionPerformed
    
    /**
     * Knappevent för open knappen
     * @param evt Action event
     */
    private void menuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenActionPerformed
        Player tmp = mod.loadHero();
        if(tmp != null){
            
            enableButtons(true);
            this.updateGearLbls();
            updateInventory(mod.getHero());
            updateHeroPnl(tmp);
        }
        
    }//GEN-LAST:event_menuItemOpenActionPerformed
    
    /**
     * Knappevent för btnBuy2hand
     * @param evt Action event
     */
    private void btnBuy2HandedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuy2HandedActionPerformed
        
        Weapon wep = new TwoHanded("dummy weapon");
        int i = cmb2Handed.getSelectedIndex();
        wep = wep.createWeapon(i);
        if(mod.getHero().getLvl() >= wep.getLvlReq()){
        mod.addWeapon(wep);
        updateHeroPnl(mod.getHero());
        updateInventory(mod.getHero());
        System.out.println(mod.getHero().getGold());
        }else{
            JOptionPane.showMessageDialog(null, "You don't meet the level "
                    + "requirement for this item\nClick the label to "
                    + "find out what level is needed.");
        }
        
    }//GEN-LAST:event_btnBuy2HandedActionPerformed
    
    /**
     * Knappevent för btnBuy1hand
     * @param evt Action event
     */
    private void btnBuy1HandedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuy1HandedActionPerformed
        Weapon wep = new OneHanded("dummy weapon");
        int i = cmb1Handed.getSelectedIndex();
        wep = wep.createWeapon(i);
        if(mod.getHero().getLvl() >= wep.getLvlReq()){
        mod.addWeapon(wep);
        updateHeroPnl(mod.getHero());
        updateInventory(mod.getHero());
        System.out.println(mod.getHero().getGold());
        }else{
            JOptionPane.showMessageDialog(null, "You don't meet the level "
                    + "requirement for this item\nClick the label to "
                    + "find out what level is needed.");
        }
        
    }//GEN-LAST:event_btnBuy1HandedActionPerformed
    
    /**
     * Knappevent för btnBuyShield
     * @param evt Action event
     */
    private void btnBuyShieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyShieldActionPerformed
        Weapon wep = new Shield("dummy weapon");
        int i = cmbShield.getSelectedIndex();
        wep = wep.createWeapon(i);
        if(mod.getHero().getLvl() >= wep.getLvlReq()){
        mod.addWeapon(wep);
        updateHeroPnl(mod.getHero());
        updateInventory(mod.getHero());
        System.out.println(mod.getHero().getGold());
        }else{
            JOptionPane.showMessageDialog(null, "You don't meet the level "
                    + "requirement for this item\nClick the label to "
                    + "find out what level is needed.");
        }
    }//GEN-LAST:event_btnBuyShieldActionPerformed
    
    /**
     * Knappevent för btnBuyRing
     * @param evt Action event
     */
    private void btnRingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRingActionPerformed
        Armor arm = new Ring("dummy ring");
        int i = cmbRing.getSelectedIndex();
        arm = arm.createArmor(i);
        if(mod.getHero().getLvl() >= arm.getLvlReq()){
        mod.addArmor(arm);
        updateHeroPnl(mod.getHero());
        updateInventory(mod.getHero());
        System.out.println(mod.getHero().getGold());
        }else{
            JOptionPane.showMessageDialog(null, "You don't meet the level "
                    + "requirement for this item\nClick the label to "
                    + "find out what level is needed.");
        }
    }//GEN-LAST:event_btnRingActionPerformed
    
    /**
     * Knappevent för info knapp
     * @param evt Action event
     */
    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
       String slot = jTableInv.getValueAt(jTableInv.getSelectedRow(), 2).toString();
       String name = jTableInv.getValueAt(jTableInv.getSelectedRow(), 0).toString();
       String printString = mod.getInfo(slot, name);
       JOptionPane.showMessageDialog(null, printString);
    }//GEN-LAST:event_btnInfoActionPerformed
    
    /**
     * Knappevent för btnBuyCloth
     * @param evt Action event
     */
    private void btnClothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClothActionPerformed
        Armor arm = new Cloth("dummy cloth");
        int i = cmbCloth.getSelectedIndex();
        arm = arm.createArmor(i);
        if(mod.getHero().getLvl() >= arm.getLvlReq()){
        mod.addArmor(arm);
        updateHeroPnl(mod.getHero());
        updateInventory(mod.getHero());
        System.out.println(mod.getHero().getGold());
        }else{
            JOptionPane.showMessageDialog(null, "You don't meet the level "
                    + "requirement for this item\nClick the label to "
                    + "find out what level is needed.");
        }
    }//GEN-LAST:event_btnClothActionPerformed
    
    /**
     * Knappevent för btnBuyLeather
     * @param evt Action event
     */
    private void btnLeatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeatherActionPerformed
        Armor arm = new Leather("dummy leather");
        int i = cmbLeather.getSelectedIndex();
        arm = arm.createArmor(i);
        if(mod.getHero().getLvl() >= arm.getLvlReq()){
        mod.addArmor(arm);
        updateHeroPnl(mod.getHero());
        updateInventory(mod.getHero());
        System.out.println(mod.getHero().getGold());
        }else{
            JOptionPane.showMessageDialog(null, "You don't meet the level "
                    + "requirement for this item\nClick the label to "
                    + "find out what level is needed.");
        }
    }//GEN-LAST:event_btnLeatherActionPerformed
    
    /**
     * Knappevent för btnBuyMetal
     * @param evt Action event
     */
    private void btnMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetalActionPerformed
        Armor arm = new Metal("dummy metal");
        int i = cmbMetal.getSelectedIndex();
        arm = arm.createArmor(i);
        if(mod.getHero().getLvl() >= arm.getLvlReq()){
        mod.addArmor(arm);
        updateHeroPnl(mod.getHero());
        updateInventory(mod.getHero());
        System.out.println(mod.getHero().getGold());
        }else{
            JOptionPane.showMessageDialog(null, "You don't meet the level "
                    + "requirement for this item\nClick the label to "
                    + "find out what level is needed.");
        }
    }//GEN-LAST:event_btnMetalActionPerformed
    /**
     * Knappevent för equip knapp
     * @param evt Action event
     */
    private void btnEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipActionPerformed
        String slot = jTableInv.getValueAt(jTableInv.getSelectedRow(), 2).toString();
        String name = jTableInv.getValueAt(jTableInv.getSelectedRow(), 0).toString();
        mod.equipWeapon(slot, name);
        this.updateGearLbls();
    }//GEN-LAST:event_btnEquipActionPerformed
    
    /**
     * Knappevent för lblShield
     * @param evt Action event
     */
    private void lblGearShieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGearShieldMouseClicked
        String slot = "Shield";
        mod.unequipWeapon(slot);
        this.updateGearLbls();
    }//GEN-LAST:event_lblGearShieldMouseClicked
    
    /**
     * Knappevent för lblOneHanded
     * @param evt Action event
     */
    private void lblOneHandedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOneHandedMouseClicked
        String slot = "1-Handed";
        mod.unequipWeapon(slot);
        this.updateGearLbls();
    }//GEN-LAST:event_lblOneHandedMouseClicked
    
    /**
     * Knappevent för lblTwoHanded
     * @param evt Action event
     */
    private void lblTwoHandedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTwoHandedMouseClicked
        String slot = "2-Handed";
        mod.unequipWeapon(slot);
        this.updateGearLbls();
    }//GEN-LAST:event_lblTwoHandedMouseClicked
   
    /**
     * Knappevent för lblHelm
     * @param evt Action event
     */
    private void lblHelmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHelmMouseClicked
        String slot = "Head";
        mod.unequipArmor(slot);
        this.updateGearLbls();
    }//GEN-LAST:event_lblHelmMouseClicked
    
    /**
     * Knappevent för lblChest
     * @param evt Action event
     */
    private void lblChestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChestMouseClicked
       String slot = "Chest";
        mod.unequipArmor(slot);
        this.updateGearLbls();
    }//GEN-LAST:event_lblChestMouseClicked
    
    /**
     * Knappevent för lblArm
     * @param evt Action event
     */
    private void lblArmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArmMouseClicked
       String slot = "Arm";
        mod.unequipArmor(slot);
        this.updateGearLbls();
    }//GEN-LAST:event_lblArmMouseClicked
    
    /**
     * Knappevent för lblLegs
     * @param evt Action event
     */
    private void lblLegsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLegsMouseClicked
        String slot = "Legs";
        mod.unequipArmor(slot);
        this.updateGearLbls();
    }//GEN-LAST:event_lblLegsMouseClicked
    
    /**
     * Knappevent för lblRing
     * @param evt Action event
     */
    private void lblRingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRingMouseClicked
        String slot = "Ring";
        mod.unequipArmor(slot);
        this.updateGearLbls();
    }//GEN-LAST:event_lblRingMouseClicked
    
    /**
     * Knappevent för lblFeet
     * @param evt Action event
     */
    private void lblFeetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFeetMouseClicked
        String slot = "Feet";
        mod.unequipArmor(slot);
        this.updateGearLbls();
    }//GEN-LAST:event_lblFeetMouseClicked
    
    /**
     * Knappevent för btnEnterArena
     * @param evt Action event
     */
    private void btnEnterArenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterArenaActionPerformed
        Monster monster = new Monster("dummy");
        monster = monster.createCharacter(cmbMonster.getSelectedIndex());
        Player hero = mod.getHero();
        Fight fight = new Fight(monster, hero, txaArena, btnEnterArena);
        fight.battleOn();
        updateHeroPnl(hero);
        if(fight.herolvledUP){
            setLvlUPenabled(true);
            enableButtons(false);
            txfPoints.setText("Points: 15");
            txf1h.setText("0");
            txf2h.setText("0");
            txfShield.setText("0");
            txfAgi.setText("0");
            txfStr.setText("0");
            txfTgh.setText("0");
            txfSpd.setText("0");
        }
    }//GEN-LAST:event_btnEnterArenaActionPerformed

    /**
     * Knappevent för btnSetStats
     * @param evt Action event
     */
    private void btnSetStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetStatsActionPerformed
        int tgh, oneh, twoh, shield, agi, str, spd;
        try{
        if(txf1h.getText() != null){
            oneh = Integer.parseInt(txf1h.getText());
            
        }else{
            oneh = 0;
        }
        if(txf2h.getText() != null){
            twoh = Integer.parseInt(txf2h.getText());
        }
        else{
            twoh = 0;
        }
        if(txfShield.getText() != null){
            shield = Integer.parseInt(txfShield.getText());
        }
        else{
            shield = 0;
        }
        if(txfAgi.getText() != null){
            agi = Integer.parseInt(txfAgi.getText());
        }
        else{
            agi = 0;
        }
        if(txfStr.getText() != null){
            str = Integer.parseInt(txfStr.getText());
        }
        else{
            str = 0;
        }
        if(txfTgh.getText() != null){
            tgh = Integer.parseInt(txfTgh.getText());
        }else{
            tgh = 0;
        }
        if(txfSpd.getText() != null){
            spd = Integer.parseInt(txfSpd.getText());
        }else{
            spd = 0;
        }
        int [] statsPoints = {agi, str, spd, tgh, oneh,twoh,shield};
        int sum = 0;
        for(int i : statsPoints){
            System.out.println(i);
            sum += i;
        }
        if(sum == 15){
            Player hero = mod.getHero();
            hero.levelUP(statsPoints);
            setLvlUPenabled(false);
            enableButtons(true);
            txfPoints.setText("");
            updateHeroPnl(hero);
            
        }else{
            JOptionPane.showMessageDialog(null, "The points you have spent has to add up to 15, please try agian");
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "You can only enter numbers!");
            txf1h.setText("0");
            txf2h.setText("0");
            txfShield.setText("0");
            txfAgi.setText("0");
            txfStr.setText("0");
            txfTgh.setText("0");
            txfSpd.setText("0");
        }
    }//GEN-LAST:event_btnSetStatsActionPerformed
   
    /**
     * Knappevent för lbl2Handed
     * @param evt Action event
     */
    private void lbl2HandedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2HandedMouseClicked
        Weapon wep = new TwoHanded("dummy");
        wep = wep.createWeapon(cmb2Handed.getSelectedIndex());
        JOptionPane.showMessageDialog(null, wep.getInfo());
    }//GEN-LAST:event_lbl2HandedMouseClicked
    
    /**
     * Knappevent för lbl1Handed
     * @param evt Action event
     */
    private void lbl1handedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1handedMouseClicked
        Weapon wep = new OneHanded("dummy");
        wep = wep.createWeapon(cmb1Handed.getSelectedIndex());
        JOptionPane.showMessageDialog(null, wep.getInfo());
    }//GEN-LAST:event_lbl1handedMouseClicked
    
    /**
     * Knappevent för lblShield
     * @param evt Action event
     */
    private void lblShieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShieldMouseClicked
        Weapon wep = new Shield("dummy");
        wep = wep.createWeapon(cmbShield.getSelectedIndex());
        JOptionPane.showMessageDialog(null, wep.getInfo());
    }//GEN-LAST:event_lblShieldMouseClicked
    
    /**
     * Knappevent för lblRing
     * @param evt Action event
     */
    private void lblRingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRingsMouseClicked
        Armor arm = new Ring("dummy");
        arm = arm.createArmor(cmbRing.getSelectedIndex());
        JOptionPane.showMessageDialog(null, arm.getInfo());
    }//GEN-LAST:event_lblRingsMouseClicked
    
    /**
     * Knappevent för lblMetal
     * @param evt Action event
     */
    private void lblMetalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMetalMouseClicked
        Armor arm = new Metal("dummy");
        arm = arm.createArmor(cmbMetal.getSelectedIndex());
        JOptionPane.showMessageDialog(null, arm.getInfo());
    }//GEN-LAST:event_lblMetalMouseClicked
    
    /**
     * Knappevent för lblLeather
     * @param evt Action event
     */
    private void lblLeatherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLeatherMouseClicked
        Armor arm = new Leather("dummy");
        arm = arm.createArmor(cmbLeather.getSelectedIndex());
        JOptionPane.showMessageDialog(null, arm.getInfo());
    }//GEN-LAST:event_lblLeatherMouseClicked
    
    /**
     * Knappevent för lblMarketCloth
     * @param evt Action event
     */
    private void lblMarketClothMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarketClothMouseClicked
        Armor arm = new Cloth("dummy");
        arm = arm.createArmor(cmbCloth.getSelectedIndex());
        JOptionPane.showMessageDialog(null, arm.getInfo());
    }//GEN-LAST:event_lblMarketClothMouseClicked
    
    /**
     * Knappevent för about knappen
     * @param evt Action event
     */
    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        JOptionPane.showMessageDialog(null, "This program was written by\n"
                + "Simon Horenstedt\n"
                + "Mattias Nordberg\n"
                + "Version: 1.1.0\n"
                + "\u00a9 2015-05-12 ");
    }//GEN-LAST:event_menuItemAboutActionPerformed
    /**
     * Knappevent för monster infoknapp
     * @param evt Action event
     */
    private void btnMonsterInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonsterInfoActionPerformed
        Monster m = new Monster("dummy");
        m = m.createCharacter(cmbMonster.getSelectedIndex());
        JOptionPane.showMessageDialog(null, m.getInfo());
    }//GEN-LAST:event_btnMonsterInfoActionPerformed
    
    /**
     * Gör så att det går att använda textfält och knappar för att levla up en gång.
     * @param b boolean true för redigerbara, false för icke redigerbara
     */
    private void setLvlUPenabled(boolean b){
        btnSetStats.setEnabled(b);
        txf1h.setEditable(b);
        txf2h.setEditable(b);
        txfShield.setEditable(b);
        txfAgi.setEditable(b);
        txfStr.setEditable(b);
        txfTgh.setEditable(b);
        txfSpd.setEditable(b);
        txf1h.setFocusable(b);
        txf2h.setFocusable(b);
        txfShield.setFocusable(b);
        txfAgi.setFocusable(b);
        txfStr.setFocusable(b);
        txfTgh.setFocusable(b);
        txfSpd.setFocusable(b);
        txf1h.setText("");
        txf2h.setText("");
        txfShield.setText("");
        txfAgi.setText("");
        txfStr.setText("");
        txfTgh.setText("");
        txfSpd.setText("");
        
    }
    
    /**
     * Uppdaterar table med aktuell Spelare
     * @param hero Den aktuella spelaren 
     */
    private void updateInventory(Player hero){
        int n = 0;
        for(int i = 0; i < 2; i++){
            if(i == 0){
                ArrayList <Weapon> weaponInv = hero.getWepInv();
                if(!weaponInv.isEmpty()){
                    for( Weapon wep: weaponInv){
                        String [] posts = wep.toString().split(", ");
                        for(int m = 0; m < 6; m++){
                            InventoryTable.setValueAt(posts[m], n, m);
                        }
                    n++;
                    }
                }
            }
            else if(i == 1){
                ArrayList <Armor> armInv = hero.getArmInv();
                if(!armInv.isEmpty()){
                    for(Armor arm : armInv){
                        String [] posts = arm.toString().split(", ");
                        for(int m = 0; m < 6; m++){
                            InventoryTable.setValueAt(posts[m], n, m);
                        }
                    n++;
                    }
                }               
            }
        }
    }
    
    /**
     * Uppdaterar vilket gear som är på genom att göra lbls synliga/osynliga
     */
    private void updateGearLbls(){
        Player hero = mod.getHero();
        boolean [] equipped = hero.getEquipped();
        for(int i = 0; i < equipped.length; i++){
            switch (i){
                case 0:
                    lblHelm.setVisible(equipped[i]);
                break;
                case 1:
                    lblChest.setVisible(equipped[i]);
                break;
                case 2:
                    lblArm.setVisible(equipped[i]);
                break;
                case 3:
                    lblLegs.setVisible(equipped[i]);
                break;    
                case 4:
                    lblFeet.setVisible(equipped[i]);
                break;
                case 5:
                    lblRing.setVisible(equipped[i]);
                break;    
                case 6:
                    lblGearShield.setVisible(equipped[i]);
                break;    
                case 7:
                    lblTwoHanded.setVisible(equipped[i]);
                break;    
                case 8:
                    lblOneHanded.setVisible(equipped[i]);
                break;     
            }
        }
    }
    
    /**
     * sätter Gearlbls synliga/osynliga
     * @param b false för osynlig true för synlig
     */
    private void setGearVisibility(boolean b){
        lblHelm.setVisible(b);
        lblChest.setVisible(b);
        lblArm.setVisible(b);
        lblLegs.setVisible(b);
        lblFeet.setVisible(b);
        lblRing.setVisible(b);
        lblGearShield.setVisible(b);
        lblOneHanded.setVisible(b);
        lblTwoHanded.setVisible(b);   
    }
    
    /**
     * Uppdaterar heropanelen med stats
     * @param tmp den aktuella spelaren
     */
    private void updateHeroPnl(Player tmp){
        int [] statList = tmp.getStats();
//        System.out.println(tmp.toString());
        lblGladName.setText(tmp.getName());
        lblAgi.setText("Agility: " + statList[0]);
        lblStr.setText("Strenght: " + statList[1]);
        lblSpd.setText("Speed: " + statList[2]);
        lblTgh.setText("Toughness: " + statList[3]); 
        lblOneStats.setText("1-Handed: " + statList[4]);
        lblTwoStats.setText("2-Handed: " + statList[5]);
        lblHackStats.setText("Shield: " + statList[6]);
        txfLvl.setText(Integer.toString(statList[7]));
        txfExp.setText(Integer.toString(statList[8]));
        txfHp.setText(Integer.toString(statList[9]));
        txfGold.setText(Integer.toString(statList[10]));
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy1Handed;
    private javax.swing.JButton btnBuy2Handed;
    private javax.swing.JButton btnBuyShield;
    private javax.swing.JButton btnCloth;
    private javax.swing.JButton btnEnterArena;
    private javax.swing.JButton btnEquip;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnLeather;
    private javax.swing.JButton btnMetal;
    private javax.swing.JButton btnMonsterInfo;
    private javax.swing.JButton btnRing;
    private javax.swing.JButton btnSetStats;
    private javax.swing.JComboBox cmb1Handed;
    private javax.swing.JComboBox cmb2Handed;
    private javax.swing.JComboBox cmbCloth;
    private javax.swing.JComboBox cmbLeather;
    private javax.swing.JComboBox cmbMetal;
    private javax.swing.JComboBox cmbMonster;
    private javax.swing.JComboBox cmbRing;
    private javax.swing.JComboBox cmbShield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTableInv;
    private javax.swing.JLabel lbl1handed;
    private javax.swing.JLabel lbl2Handed;
    private javax.swing.JLabel lblAgi;
    private javax.swing.JLabel lblArm;
    private javax.swing.JLabel lblChest;
    private javax.swing.JLabel lblExp;
    private javax.swing.JLabel lblFeet;
    private javax.swing.JLabel lblGearShield;
    private javax.swing.JLabel lblGladName;
    private javax.swing.JLabel lblGold;
    private javax.swing.JLabel lblHackStats;
    private javax.swing.JLabel lblHelm;
    private javax.swing.JLabel lblHp;
    private javax.swing.JLabel lblLeather;
    private javax.swing.JLabel lblLegs;
    private javax.swing.JLabel lblLvl;
    private javax.swing.JLabel lblMarketCloth;
    private javax.swing.JLabel lblMetal;
    private javax.swing.JLabel lblMonster;
    private javax.swing.JLabel lblOneHanded;
    private javax.swing.JLabel lblOneStats;
    private javax.swing.JLabel lblRing;
    private javax.swing.JLabel lblRings;
    private javax.swing.JLabel lblShield;
    private javax.swing.JLabel lblSpd;
    private javax.swing.JLabel lblStats;
    private javax.swing.JLabel lblStr;
    private javax.swing.JLabel lblTgh;
    private javax.swing.JLabel lblTwoHanded;
    private javax.swing.JLabel lblTwoStats;
    private javax.swing.JLabel lblWepSkills;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemHelp;
    private javax.swing.JMenuItem menuItemNew;
    private javax.swing.JMenuItem menuItemOpen;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JPanel pnl1handedMarket;
    private javax.swing.JPanel pnl2HandedMarket;
    private javax.swing.JPanel pnlArena;
    private javax.swing.JPanel pnlArenaOpt;
    private javax.swing.JPanel pnlArmorMarket;
    private javax.swing.JPanel pnlCharacter;
    private javax.swing.JPanel pnlGear;
    private javax.swing.JPanel pnlHero;
    private javax.swing.JPanel pnlMarketplace;
    private javax.swing.JPanel pnlShieldMarket;
    private javax.swing.JTabbedPane tabMarket;
    private javax.swing.JTextArea txaArena;
    private javax.swing.JTextField txf1h;
    private javax.swing.JTextField txf2h;
    private javax.swing.JTextField txfAgi;
    private javax.swing.JTextField txfExp;
    private javax.swing.JTextField txfGold;
    private javax.swing.JTextField txfHp;
    private javax.swing.JTextField txfLvl;
    private javax.swing.JTextField txfPoints;
    private javax.swing.JTextField txfShield;
    private javax.swing.JTextField txfSpd;
    private javax.swing.JTextField txfStr;
    private javax.swing.JTextField txfTgh;
    // End of variables declaration//GEN-END:variables
}
