
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 96simrog
 */
public class GUI extends javax.swing.JFrame {
    ImageIcon img;
    InventoryTableModel InventoryTable;
    Model mod;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        mod = new Model();
        img = new ImageIcon("../Projektuppgiften/icon.PNG");
        InventoryTable = new InventoryTableModel();
        this.setIconImage(img.getImage());
        jTableInv.setModel(InventoryTable);  
        setGearVisibility(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlMarketplace = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tabMarket = new javax.swing.JTabbedPane();
        pnl2HandedMarket = new javax.swing.JPanel();
        cmb2Handed = new javax.swing.JComboBox();
        lbl2Handed = new javax.swing.JLabel();
        btnBuy2Handed = new javax.swing.JButton();
        pnl1handedMarket = new javax.swing.JPanel();
        cmb1Handed = new javax.swing.JComboBox();
        lbl1handed = new javax.swing.JLabel();
        btnBuy1Handed = new javax.swing.JButton();
        pnlShieldMarket = new javax.swing.JPanel();
        cmbShield = new javax.swing.JComboBox();
        lblShield = new javax.swing.JLabel();
        btnBuyShield = new javax.swing.JButton();
        pnlArmorMarket = new javax.swing.JPanel();
        cmbCloth = new javax.swing.JComboBox();
        cmbLeather = new javax.swing.JComboBox();
        cmbMetal = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        lblLeather = new javax.swing.JLabel();
        lblMetal = new javax.swing.JLabel();
        cmbRing = new javax.swing.JComboBox();
        lblRings = new javax.swing.JLabel();
        btnCloth = new javax.swing.JButton();
        btnLeather = new javax.swing.JButton();
        btnMetal = new javax.swing.JButton();
        btnRing = new javax.swing.JButton();
        pnlArena = new javax.swing.JPanel();
        pnlHero = new javax.swing.JPanel();
        lblAgi = new javax.swing.JLabel();
        lblStr = new javax.swing.JLabel();
        lblSpd = new javax.swing.JLabel();
        lblTgh = new javax.swing.JLabel();
        lblWepSkills = new javax.swing.JLabel();
        lblStats = new javax.swing.JLabel();
        lblOneStats = new javax.swing.JLabel();
        lblTwoStats = new javax.swing.JLabel();
        lblHackStats = new javax.swing.JLabel();
        lblStabStats = new javax.swing.JLabel();
        lblCrushStats = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblChest = new javax.swing.JLabel();
        lblHelm = new javax.swing.JLabel();
        lblArm = new javax.swing.JLabel();
        lblLegs = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblRing = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInv = new javax.swing.JTable();
        btnEquip = new javax.swing.JButton();
        btnSetStats = new javax.swing.JButton();
        pnlCharacter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblGladName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLvl = new javax.swing.JLabel();
        lblExp = new javax.swing.JLabel();
        lblHp = new javax.swing.JLabel();
        lblGold = new javax.swing.JLabel();
        txfLvl = new javax.swing.JTextField();
        txfExp = new javax.swing.JTextField();
        txfHp = new javax.swing.JTextField();
        txfGold = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItemSave = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuItemOpen = new javax.swing.JMenuItem();
        menuItemNew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();
        menuItemHelp = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab1", jPanel6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gladiator III");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Marketplace.PNG"))); // NOI18N

        cmb2Handed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Sword", "Basic Mace", "Basic Spear", "Frostmourne", "Sulfuras", "Dragon Glavie" }));
        cmb2Handed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb2HandedActionPerformed(evt);
            }
        });

        btnBuy2Handed.setText("Buy 2-Handed Weapon");
        btnBuy2Handed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuy2HandedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl2HandedMarketLayout = new javax.swing.GroupLayout(pnl2HandedMarket);
        pnl2HandedMarket.setLayout(pnl2HandedMarketLayout);
        pnl2HandedMarketLayout.setHorizontalGroup(
            pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2HandedMarketLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuy2Handed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb2Handed, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(lbl2Handed, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        pnl2HandedMarketLayout.setVerticalGroup(
            pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2HandedMarketLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2HandedMarketLayout.createSequentialGroup()
                        .addComponent(cmb2Handed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btnBuy2Handed)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2HandedMarketLayout.createSequentialGroup()
                        .addComponent(lbl2Handed, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        tabMarket.addTab("2-Handed Weapons", pnl2HandedMarket);

        cmb1Handed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Axe", "Small Basic Mace", "Basic Dagger", "Shadowmourne", "Morningstar of Agmar", "Fangs of the Father" }));
        cmb1Handed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1HandedActionPerformed(evt);
            }
        });

        btnBuy1Handed.setText("Buy 1-Handed Weapon");
        btnBuy1Handed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuy1HandedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl1handedMarketLayout = new javax.swing.GroupLayout(pnl1handedMarket);
        pnl1handedMarket.setLayout(pnl1handedMarketLayout);
        pnl1handedMarketLayout.setHorizontalGroup(
            pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1handedMarketLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuy1Handed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb1Handed, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(lbl1handed, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        pnl1handedMarketLayout.setVerticalGroup(
            pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1handedMarketLayout.createSequentialGroup()
                .addGroup(pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1handedMarketLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(cmb1Handed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnBuy1Handed))
                    .addGroup(pnl1handedMarketLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbl1handed, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tabMarket.addTab("1-Handed Weapons", pnl1handedMarket);

        cmbShield.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Round Shield", "Roman Shield" }));
        cmbShield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbShieldActionPerformed(evt);
            }
        });

        btnBuyShield.setText("Buy Shield");

        javax.swing.GroupLayout pnlShieldMarketLayout = new javax.swing.GroupLayout(pnlShieldMarket);
        pnlShieldMarket.setLayout(pnlShieldMarketLayout);
        pnlShieldMarketLayout.setHorizontalGroup(
            pnlShieldMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShieldMarketLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(pnlShieldMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbShield, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuyShield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(lblShield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        pnlShieldMarketLayout.setVerticalGroup(
            pnlShieldMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShieldMarketLayout.createSequentialGroup()
                .addGroup(pnlShieldMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlShieldMarketLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblShield, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlShieldMarketLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(cmbShield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuyShield)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabMarket.addTab("Shields", pnlShieldMarket);

        cmbCloth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Helm", "Upperbody", "Lowerbody", "Arms", "Feet" }));

        cmbLeather.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Helm", "Upperbody", "Lowerbody", "Arms", "Feet" }));

        cmbMetal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Helm", "Upperbody", "Lowerbody", "Arms", "Feet" }));

        jLabel23.setText("Cloth Armor");

        lblLeather.setText("Leather Armor");

        lblMetal.setText("Metal Armor");

        cmbRing.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Band of Pain", "Signet of Speed", "Legendary Amulet" }));

        lblRings.setText("Rings");

        btnCloth.setText("Buy Cloth");

        btnLeather.setText("Buy Leather");

        btnMetal.setText("Buy Metal");

        btnRing.setText("Buy Ring");

        javax.swing.GroupLayout pnlArmorMarketLayout = new javax.swing.GroupLayout(pnlArmorMarket);
        pnlArmorMarket.setLayout(pnlArmorMarketLayout);
        pnlArmorMarketLayout.setHorizontalGroup(
            pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArmorMarketLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlArmorMarketLayout.createSequentialGroup()
                            .addComponent(cmbCloth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArmorMarketLayout.createSequentialGroup()
                            .addComponent(btnCloth)
                            .addGap(57, 57, 57)))
                    .addGroup(pnlArmorMarketLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(79, 79, 79)))
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeather)
                    .addComponent(btnLeather)
                    .addComponent(cmbLeather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMetal)
                    .addComponent(cmbMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMetal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbRing, 0, 123, Short.MAX_VALUE)
                    .addComponent(lblRings)
                    .addComponent(btnRing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        pnlArmorMarketLayout.setVerticalGroup(
            pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArmorMarketLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblLeather)
                    .addComponent(lblMetal)
                    .addComponent(lblRings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCloth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLeather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCloth)
                    .addComponent(btnMetal)
                    .addComponent(btnLeather)
                    .addComponent(btnRing))
                .addGap(73, 73, 73))
        );

        tabMarket.addTab("Armor", pnlArmorMarket);

        javax.swing.GroupLayout pnlMarketplaceLayout = new javax.swing.GroupLayout(pnlMarketplace);
        pnlMarketplace.setLayout(pnlMarketplaceLayout);
        pnlMarketplaceLayout.setHorizontalGroup(
            pnlMarketplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarketplaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMarketplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabMarket)
                    .addGroup(pnlMarketplaceLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMarketplaceLayout.setVerticalGroup(
            pnlMarketplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarketplaceLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Marketplace", pnlMarketplace);

        pnlArena.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlArenaLayout = new javax.swing.GroupLayout(pnlArena);
        pnlArena.setLayout(pnlArenaLayout);
        pnlArenaLayout.setHorizontalGroup(
            pnlArenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        pnlArenaLayout.setVerticalGroup(
            pnlArenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Arena", pnlArena);

        lblAgi.setText("Agility:");

        lblStr.setText("Strength:");

        lblSpd.setText("Speed: ");

        lblTgh.setText("Toughness: ");

        lblWepSkills.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblWepSkills.setText("Weapon Skills");

        lblStats.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStats.setText("Stats");

        lblOneStats.setText("1-Handed:");

        lblTwoStats.setText("2-Handed:");

        lblHackStats.setText("Hack:");

        lblStabStats.setText("Stab:");

        lblCrushStats.setText("Crush: ");

        jTextField2.setEditable(false);
        jTextField2.setFocusable(false);

        jTextField4.setEditable(false);
        jTextField4.setFocusable(false);

        jTextField6.setEditable(false);
        jTextField6.setFocusable(false);

        jTextField7.setEditable(false);
        jTextField7.setFocusable(false);

        jTextField8.setEditable(false);
        jTextField8.setFocusable(false);

        jTextField9.setEditable(false);
        jTextField9.setFocusable(false);

        jTextField10.setEditable(false);
        jTextField10.setFocusable(false);

        jTextField11.setEditable(false);
        jTextField11.setFocusable(false);

        jTextField12.setEditable(false);
        jTextField12.setFocusable(false);

        jPanel5.setMinimumSize(new java.awt.Dimension(401, 449));

        lblChest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/breast.png"))); // NOI18N
        lblChest.setText("HARNESK");

        lblHelm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/helm.png"))); // NOI18N
        lblHelm.setText(" HJÄLM");

        lblArm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arm.png"))); // NOI18N
        lblArm.setText("ARM");

        lblLegs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legs.png"))); // NOI18N
        lblLegs.setText("BEN");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandal.png"))); // NOI18N
        jLabel19.setText("SKOR");

        lblRing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ring.png"))); // NOI18N
        lblRing.setText("RING");

        jLabel21.setText("2-HAND");

        jLabel25.setText("1-HAND");

        jLabel22.setText("SKÖLD");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLegs, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChest, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRing, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(lblHelm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHelm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblChest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLegs, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblArm, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblRing, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jScrollPane1.setViewportView(jTableInv);

        btnEquip.setText("Equip/Uneqiup");

        btnSetStats.setText("Set Stats");

        javax.swing.GroupLayout pnlHeroLayout = new javax.swing.GroupLayout(pnlHero);
        pnlHero.setLayout(pnlHeroLayout);
        pnlHeroLayout.setHorizontalGroup(
            pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEquip)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblCrushStats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblStabStats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblHackStats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblTwoStats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblOneStats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblTgh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblWepSkills)
                                .addGap(0, 166, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeroLayout.createSequentialGroup()
                                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSpd)
                                    .addComponent(lblStr)
                                    .addComponent(lblAgi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                            .addGroup(pnlHeroLayout.createSequentialGroup()
                                .addComponent(lblStats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSetStats)))))
                .addContainerGap())
        );
        pnlHeroLayout.setVerticalGroup(
            pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeroLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEquip)
                        .addGap(16, 16, 16)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStats)
                            .addComponent(btnSetStats))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAgi)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStr)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSpd)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTgh)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblWepSkills)
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOneStats)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTwoStats)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHackStats)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStabStats)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCrushStats)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jTabbedPane1.addTab("Hero", pnlHero);

        pnlCharacter.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Character", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP)), "Character", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP))));
        pnlCharacter.setPreferredSize(new java.awt.Dimension(216, 782));

        jLabel1.setText("BILD");

        lblGladName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGladName.setText("Name:");

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblLvl.setText("Level:");

        lblExp.setText("Exp:");

        lblHp.setText("HP:");

        lblGold.setText("Gold:");

        txfLvl.setEditable(false);
        txfLvl.setFocusable(false);

        txfExp.setEditable(false);
        txfExp.setFocusable(false);

        txfHp.setEditable(false);
        txfHp.setFocusable(false);

        txfGold.setEditable(false);
        txfGold.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLvl)
                    .addComponent(lblExp)
                    .addComponent(lblHp)
                    .addComponent(lblGold))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfLvl, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txfExp)
                    .addComponent(txfHp)
                    .addComponent(txfGold))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLvl)
                    .addComponent(txfLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExp)
                    .addComponent(txfExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHp)
                    .addComponent(txfHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGold)
                    .addComponent(txfGold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCharacterLayout = new javax.swing.GroupLayout(pnlCharacter);
        pnlCharacter.setLayout(pnlCharacterLayout);
        pnlCharacterLayout.setHorizontalGroup(
            pnlCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCharacterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCharacterLayout.createSequentialGroup()
                        .addGroup(pnlCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGladName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCharacterLayout.setVerticalGroup(
            pnlCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCharacterLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblGladName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuItemSave.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Save");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuItemSave.add(jMenuItem1);

        menuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuItemOpen.setText("Open");
        menuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenActionPerformed(evt);
            }
        });
        menuItemSave.add(menuItemOpen);

        menuItemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuItemNew.setText("New");
        menuItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewActionPerformed(evt);
            }
        });
        menuItemSave.add(menuItemNew);
        menuItemSave.add(jSeparator1);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuItemExit.setText("Exit...");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuItemSave.add(menuItemExit);

        jMenuBar1.add(menuItemSave);

        jMenu2.setText("Help");

        menuItemAbout.setText("About");
        jMenu2.add(menuItemAbout);

        menuItemHelp.setText("Help");
        menuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHelpActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemHelp);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0)
                .addComponent(pnlCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pnlCharacter, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHelpActionPerformed
       JOptionPane.showMessageDialog(null, "r u a n0b?");
    }//GEN-LAST:event_menuItemHelpActionPerformed

    private void cmb2HandedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb2HandedActionPerformed
        switch(cmb2Handed.getSelectedIndex()){
            case 1: 
                lbl2Handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2hmace1.PNG")));
            break;
            case 2: 
                lbl2Handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spear1.PNG")));
            break;
            case 3: 
                lbl2Handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sword2.PNG")));
            break;    
            case 4: 
                lbl2Handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2hmace2.PNG")));
            break;    
            case 5: 
                lbl2Handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spear2.PNG")));
            break;
            default:
                lbl2Handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sword1.png")));
            break;
        }
    }//GEN-LAST:event_cmb2HandedActionPerformed

    private void cmb1HandedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1HandedActionPerformed
        switch(cmb1Handed.getSelectedIndex()){
            case 1: 
                lbl1handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1hmace1.png")));
            break;
            case 2: 
                lbl1handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dagger1.PNG")));
            break;
            case 3: 
                lbl1handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/axe2.PNG")));
            break;
            case 4: 
                lbl1handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1hmace2.PNG")));
            break;
            case 5: 
                lbl1handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dagger2.PNG")));
            break;
            default:
                lbl1handed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/axe1.png")));
            break;
        }
    }//GEN-LAST:event_cmb1HandedActionPerformed

    private void cmbShieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbShieldActionPerformed
        switch(cmbShield.getSelectedIndex()){
            case 1: 
                lblShield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/romersk.png")));
            break;
            default:
                lblShield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rundsköld.png")));
            break;
        }
    }//GEN-LAST:event_cmbShieldActionPerformed
    
    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Do you really wish to exit the program?", "Exit?", JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION){
        System.exit(EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewActionPerformed
        
        
        String newHeroName = JOptionPane.showInputDialog(null,
                "Please choose a name for your gladiator:",
                "New gladiator:", 
                JOptionPane.PLAIN_MESSAGE);
        Player tmp = mod.createHero(newHeroName);
        this.updateHeroPnl(tmp);
        
        
        
    }//GEN-LAST:event_menuItemNewActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        mod.saveHero();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenActionPerformed
        Player tmp = mod.loadHero();
        updateHeroPnl(tmp);
    }//GEN-LAST:event_menuItemOpenActionPerformed

    private void btnBuy2HandedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuy2HandedActionPerformed
        TwoHanded wep = null;
        int i = cmb2Handed.getSelectedIndex();
        switch(i){
            case 1:
                wep = wep.createWeapon(i);
            break;
            case 2:
                wep = wep.createWeapon(i);
            break;
            case 3:
                wep = wep.createWeapon(i);
                
            break;    
            case 4:
                wep = wep.createWeapon(i);
            break;    
            case 5:
                wep = wep.createWeapon(i);
            break; 
            default:
                wep = wep.createWeapon(i);
            break;    
        
        }
        mod.addWeapon(wep);
        
        
    }//GEN-LAST:event_btnBuy2HandedActionPerformed

    private void btnBuy1HandedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuy1HandedActionPerformed
        OneHanded wep = null;
        int i = cmb1Handed.getSelectedIndex();
        switch(i){
            case 1:
                wep = wep.createWeapon(i);
            break;
            case 2:
                wep = wep.createWeapon(i);
            break;
            case 3:
                wep = wep.createWeapon(i);
                
            break;    
            case 4:
                wep = wep.createWeapon(i);
            break;    
            case 5:
                wep = wep.createWeapon(i);
            break; 
            default:
                wep = wep.createWeapon(i);
            break;    
        
        }
        mod.addWeapon(wep);
    }//GEN-LAST:event_btnBuy1HandedActionPerformed
    private void setGearVisibility(boolean b){
        lblHelm.setVisible(b);
        lblChest.setVisible(b);
        lblArm.setVisible(b);
        lblLegs.setVisible(b);
        jLabel19.setVisible(b);
        lblRing.setVisible(b);
        jLabel22.setVisible(b);
        jLabel25.setVisible(b);
        jLabel21.setVisible(b);
        
        
    }
    private void updateHeroPnl(Player tmp){
        int [] statList = tmp.getStats();
//        System.out.println(tmp.toString());
        lblGladName.setText(tmp.getName());
        lblAgi.setText("Agility: " + statList[0]);
        lblStr.setText("Strenght: " + statList[1]);
        lblSpd.setText("Speed: " + statList[2]);
        lblTgh.setText("Toughness: " + statList[3]); 
        lblOneStats.setText("1-Handed: " + statList[4]);
        lblTwoStats.setText("2-Handed: " + statList[5]);
        lblHackStats.setText("Hack: " + statList[6]);
        lblStabStats.setText("Stab: " + statList[7]);
        lblCrushStats.setText("Crush: " + statList[8]);
        txfLvl.setText(Integer.toString(statList[9]));
        txfExp.setText(Integer.toString(statList[10]));
        txfHp.setText(Integer.toString(statList[11]));
        txfGold.setText(Integer.toString(statList[12]));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy1Handed;
    private javax.swing.JButton btnBuy2Handed;
    private javax.swing.JButton btnBuyShield;
    private javax.swing.JButton btnCloth;
    private javax.swing.JButton btnEquip;
    private javax.swing.JButton btnLeather;
    private javax.swing.JButton btnMetal;
    private javax.swing.JButton btnRing;
    private javax.swing.JButton btnSetStats;
    private javax.swing.JComboBox cmb1Handed;
    private javax.swing.JComboBox cmb2Handed;
    private javax.swing.JComboBox cmbCloth;
    private javax.swing.JComboBox cmbLeather;
    private javax.swing.JComboBox cmbMetal;
    private javax.swing.JComboBox cmbRing;
    private javax.swing.JComboBox cmbShield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTableInv;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbl1handed;
    private javax.swing.JLabel lbl2Handed;
    private javax.swing.JLabel lblAgi;
    private javax.swing.JLabel lblArm;
    private javax.swing.JLabel lblChest;
    private javax.swing.JLabel lblCrushStats;
    private javax.swing.JLabel lblExp;
    private javax.swing.JLabel lblGladName;
    private javax.swing.JLabel lblGold;
    private javax.swing.JLabel lblHackStats;
    private javax.swing.JLabel lblHelm;
    private javax.swing.JLabel lblHp;
    private javax.swing.JLabel lblLeather;
    private javax.swing.JLabel lblLegs;
    private javax.swing.JLabel lblLvl;
    private javax.swing.JLabel lblMetal;
    private javax.swing.JLabel lblOneStats;
    private javax.swing.JLabel lblRing;
    private javax.swing.JLabel lblRings;
    private javax.swing.JLabel lblShield;
    private javax.swing.JLabel lblSpd;
    private javax.swing.JLabel lblStabStats;
    private javax.swing.JLabel lblStats;
    private javax.swing.JLabel lblStr;
    private javax.swing.JLabel lblTgh;
    private javax.swing.JLabel lblTwoStats;
    private javax.swing.JLabel lblWepSkills;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemHelp;
    private javax.swing.JMenuItem menuItemNew;
    private javax.swing.JMenuItem menuItemOpen;
    private javax.swing.JMenu menuItemSave;
    private javax.swing.JPanel pnl1handedMarket;
    private javax.swing.JPanel pnl2HandedMarket;
    private javax.swing.JPanel pnlArena;
    private javax.swing.JPanel pnlArmorMarket;
    private javax.swing.JPanel pnlCharacter;
    private javax.swing.JPanel pnlHero;
    private javax.swing.JPanel pnlMarketplace;
    private javax.swing.JPanel pnlShieldMarket;
    private javax.swing.JTabbedPane tabMarket;
    private javax.swing.JTextField txfExp;
    private javax.swing.JTextField txfGold;
    private javax.swing.JTextField txfHp;
    private javax.swing.JTextField txfLvl;
    // End of variables declaration//GEN-END:variables
}
