
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 96simrog
 */
public class GUI extends javax.swing.JFrame {
    ImageIcon img = new ImageIcon("../Projektuppgiften/icon.PNG");
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.setIconImage(img.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlMarketplace = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tabMarket = new javax.swing.JTabbedPane();
        pnl2HandedMarket = new javax.swing.JPanel();
        cmbSword = new javax.swing.JComboBox();
        lblSword = new javax.swing.JLabel();
        cmbMace = new javax.swing.JComboBox();
        cmbSpear = new javax.swing.JComboBox();
        lblMace = new javax.swing.JLabel();
        lblSpear = new javax.swing.JLabel();
        btnBuySword = new javax.swing.JButton();
        btnBuy2hMace = new javax.swing.JButton();
        btnBuySpear = new javax.swing.JButton();
        pnl1handedMarket = new javax.swing.JPanel();
        cmbAxe = new javax.swing.JComboBox();
        cmb1hMace = new javax.swing.JComboBox();
        cmbDagger = new javax.swing.JComboBox();
        lblAxe = new javax.swing.JLabel();
        lbl1hMace = new javax.swing.JLabel();
        lblDagger = new javax.swing.JLabel();
        btnBuyDagger = new javax.swing.JButton();
        btnBuy1hMace = new javax.swing.JButton();
        btnBuyAxe = new javax.swing.JButton();
        pnlShieldMarket = new javax.swing.JPanel();
        cmbShield = new javax.swing.JComboBox();
        lblShield = new javax.swing.JLabel();
        btnBuyShield = new javax.swing.JButton();
        pnlArmorMarket = new javax.swing.JPanel();
        cmbCloth = new javax.swing.JComboBox();
        cmbLeather = new javax.swing.JComboBox();
        cmbMetal = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        lblLeather = new javax.swing.JLabel();
        lblMetal = new javax.swing.JLabel();
        cmbRing = new javax.swing.JComboBox();
        lblRings = new javax.swing.JLabel();
        btnCloth = new javax.swing.JButton();
        btnLeather = new javax.swing.JButton();
        btnMetal = new javax.swing.JButton();
        btnRing = new javax.swing.JButton();
        pnlArena = new javax.swing.JPanel();
        pnlHero = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlCharacter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblGladName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLvl = new javax.swing.JLabel();
        lblExp = new javax.swing.JLabel();
        lblHp = new javax.swing.JLabel();
        lblGold = new javax.swing.JLabel();
        txfLvl = new javax.swing.JTextField();
        txfExp = new javax.swing.JTextField();
        txfHp = new javax.swing.JTextField();
        txfGold = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab1", jPanel6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gladiator III");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Marketplace.PNG"))); // NOI18N

        cmbSword.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Sword", "Frostmourne" }));
        cmbSword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSwordActionPerformed(evt);
            }
        });

        cmbMace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Big Basic Mace", "Sulfuras" }));
        cmbMace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMaceActionPerformed(evt);
            }
        });

        cmbSpear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Spear", "Dragon Glavie" }));
        cmbSpear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSpearActionPerformed(evt);
            }
        });

        btnBuySword.setText("Buy Sword");

        btnBuy2hMace.setText("Buy Mace");
        btnBuy2hMace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuy2hMaceActionPerformed(evt);
            }
        });

        btnBuySpear.setText("Buy Spear");

        javax.swing.GroupLayout pnl2HandedMarketLayout = new javax.swing.GroupLayout(pnl2HandedMarket);
        pnl2HandedMarket.setLayout(pnl2HandedMarketLayout);
        pnl2HandedMarketLayout.setHorizontalGroup(
            pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2HandedMarketLayout.createSequentialGroup()
                .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2HandedMarketLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSword, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuySword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnl2HandedMarketLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblSword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2HandedMarketLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbMace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuy2hMace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnl2HandedMarketLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblMace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2HandedMarketLayout.createSequentialGroup()
                        .addComponent(lblSpear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2HandedMarketLayout.createSequentialGroup()
                        .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBuySpear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSpear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(78, 78, 78))))
        );
        pnl2HandedMarketLayout.setVerticalGroup(
            pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2HandedMarketLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSpear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblMace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSpear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(lblSword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(pnl2HandedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuySword)
                    .addComponent(btnBuy2hMace)
                    .addComponent(btnBuySpear))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabMarket.addTab("2-Handed Weapons", pnl2HandedMarket);

        cmbAxe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Axe", "Shadowmourne" }));
        cmbAxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAxeActionPerformed(evt);
            }
        });

        cmb1hMace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Small Basic Mace", "Morningstar of Angmar" }));
        cmb1hMace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1hMaceActionPerformed(evt);
            }
        });

        cmbDagger.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Dagger", "Fangs of the Father" }));
        cmbDagger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDaggerActionPerformed(evt);
            }
        });

        btnBuyDagger.setText("Buy Dagger");

        btnBuy1hMace.setText("Buy Mace");

        btnBuyAxe.setText("Buy Axe");

        javax.swing.GroupLayout pnl1handedMarketLayout = new javax.swing.GroupLayout(pnl1handedMarket);
        pnl1handedMarket.setLayout(pnl1handedMarketLayout);
        pnl1handedMarketLayout.setHorizontalGroup(
            pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1handedMarketLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbAxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1handedMarketLayout.createSequentialGroup()
                        .addComponent(lblAxe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addComponent(btnBuyAxe, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl1handedMarketLayout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(cmb1hMace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl1handedMarketLayout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(lbl1hMace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl1handedMarketLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuy1hMace, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuyDagger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbDagger, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl1handedMarketLayout.createSequentialGroup()
                        .addComponent(lblDagger, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGap(56, 56, 56))
        );
        pnl1handedMarketLayout.setVerticalGroup(
            pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1handedMarketLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb1hMace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDagger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblAxe, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(lblDagger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl1hMace, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1handedMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuyDagger)
                    .addComponent(btnBuy1hMace)
                    .addComponent(btnBuyAxe))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabMarket.addTab("1-Handed Weapons", pnl1handedMarket);

        cmbShield.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Round Shield", "Roman Shield" }));
        cmbShield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbShieldActionPerformed(evt);
            }
        });

        btnBuyShield.setText("Buy Shield");

        javax.swing.GroupLayout pnlShieldMarketLayout = new javax.swing.GroupLayout(pnlShieldMarket);
        pnlShieldMarket.setLayout(pnlShieldMarketLayout);
        pnlShieldMarketLayout.setHorizontalGroup(
            pnlShieldMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShieldMarketLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(pnlShieldMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbShield, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuyShield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(lblShield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        pnlShieldMarketLayout.setVerticalGroup(
            pnlShieldMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShieldMarketLayout.createSequentialGroup()
                .addGroup(pnlShieldMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlShieldMarketLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblShield, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlShieldMarketLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(cmbShield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuyShield)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        tabMarket.addTab("Shields", pnlShieldMarket);

        cmbCloth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Helm", "Upperbody", "Lowerbody", "Arms", "Feet" }));

        cmbLeather.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Helm", "Upperbody", "Lowerbody", "Arms", "Feet" }));

        cmbMetal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Helm", "Upperbody", "Lowerbody", "Arms", "Feet" }));

        jLabel23.setText("Cloth Armor");

        lblLeather.setText("Leather Armor");

        lblMetal.setText("Metal Armor");

        cmbRing.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Band of Pain", "Signet of Speed", "Legendary Amulet" }));

        lblRings.setText("Rings");

        btnCloth.setText("Buy Cloth");

        btnLeather.setText("Buy Leather");

        btnMetal.setText("Buy Metal");

        btnRing.setText("Buy Ring");

        javax.swing.GroupLayout pnlArmorMarketLayout = new javax.swing.GroupLayout(pnlArmorMarket);
        pnlArmorMarket.setLayout(pnlArmorMarketLayout);
        pnlArmorMarketLayout.setHorizontalGroup(
            pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArmorMarketLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlArmorMarketLayout.createSequentialGroup()
                            .addComponent(cmbCloth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArmorMarketLayout.createSequentialGroup()
                            .addComponent(btnCloth)
                            .addGap(57, 57, 57)))
                    .addGroup(pnlArmorMarketLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(79, 79, 79)))
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeather)
                    .addComponent(btnLeather)
                    .addComponent(cmbLeather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMetal)
                    .addComponent(cmbMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMetal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbRing, 0, 123, Short.MAX_VALUE)
                    .addComponent(lblRings)
                    .addComponent(btnRing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        pnlArmorMarketLayout.setVerticalGroup(
            pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArmorMarketLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblLeather)
                    .addComponent(lblMetal)
                    .addComponent(lblRings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCloth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLeather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(pnlArmorMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCloth)
                    .addComponent(btnMetal)
                    .addComponent(btnLeather)
                    .addComponent(btnRing))
                .addGap(73, 73, 73))
        );

        tabMarket.addTab("Armor", pnlArmorMarket);

        javax.swing.GroupLayout pnlMarketplaceLayout = new javax.swing.GroupLayout(pnlMarketplace);
        pnlMarketplace.setLayout(pnlMarketplaceLayout);
        pnlMarketplaceLayout.setHorizontalGroup(
            pnlMarketplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarketplaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMarketplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabMarket)
                    .addGroup(pnlMarketplaceLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMarketplaceLayout.setVerticalGroup(
            pnlMarketplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarketplaceLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Marketplace", pnlMarketplace);

        pnlArena.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlArenaLayout = new javax.swing.GroupLayout(pnlArena);
        pnlArena.setLayout(pnlArenaLayout);
        pnlArenaLayout.setHorizontalGroup(
            pnlArenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        pnlArenaLayout.setVerticalGroup(
            pnlArenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Arena", pnlArena);

        jLabel2.setText("BILD");

        jLabel3.setText("Agility:");

        jLabel4.setText("Strength:");

        jLabel5.setText("Speed: ");

        jLabel6.setText("Toughness: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Weapon Skills");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Stats");

        jLabel10.setText("1-Handed:");

        jLabel11.setText("2-Handed:");

        jLabel12.setText("Hack:");

        jLabel13.setText("Stab:");

        jLabel14.setText("Crush: ");

        jTextField2.setEditable(false);
        jTextField2.setFocusable(false);

        jTextField4.setEditable(false);
        jTextField4.setFocusable(false);

        jTextField6.setEditable(false);
        jTextField6.setFocusable(false);

        jTextField7.setEditable(false);
        jTextField7.setFocusable(false);

        jTextField8.setEditable(false);
        jTextField8.setFocusable(false);

        jTextField9.setEditable(false);
        jTextField9.setFocusable(false);

        jTextField10.setEditable(false);
        jTextField10.setFocusable(false);

        jTextField11.setEditable(false);
        jTextField11.setFocusable(false);

        jTextField12.setEditable(false);
        jTextField12.setFocusable(false);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/breast.png"))); // NOI18N
        jLabel15.setText("HARNESK");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/helm.png"))); // NOI18N
        jLabel16.setText(" HJÄLM");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arm.png"))); // NOI18N
        jLabel17.setText("ARM");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/legs.png"))); // NOI18N
        jLabel18.setText("BEN");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandal.png"))); // NOI18N
        jLabel19.setText("SKOR");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ring.png"))); // NOI18N
        jLabel20.setText("RING");

        jLabel21.setText("2-HAND");

        jLabel25.setText("1-HAND");

        jLabel22.setText("SKÖLD");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlHeroLayout = new javax.swing.GroupLayout(pnlHero);
        pnlHero.setLayout(pnlHeroLayout);
        pnlHeroLayout.setHorizontalGroup(
            pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeroLayout.createSequentialGroup()
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlHeroLayout.setVerticalGroup(
            pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeroLayout.createSequentialGroup()
                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeroLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlHeroLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Hero", pnlHero);

        pnlCharacter.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Character", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP)), "Character", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP))));
        pnlCharacter.setPreferredSize(new java.awt.Dimension(216, 782));

        jLabel1.setText("BILD");

        lblGladName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGladName.setText("Name:");

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblLvl.setText("Level:");

        lblExp.setText("Exp:");

        lblHp.setText("HP:");

        lblGold.setText("Gold:");

        txfLvl.setEditable(false);
        txfLvl.setFocusable(false);

        txfExp.setEditable(false);
        txfExp.setFocusable(false);

        txfHp.setEditable(false);
        txfHp.setFocusable(false);

        txfGold.setEditable(false);
        txfGold.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLvl)
                    .addComponent(lblExp)
                    .addComponent(lblHp)
                    .addComponent(lblGold))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfLvl, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txfExp)
                    .addComponent(txfHp)
                    .addComponent(txfGold))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLvl)
                    .addComponent(txfLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExp)
                    .addComponent(txfExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHp)
                    .addComponent(txfHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGold)
                    .addComponent(txfGold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCharacterLayout = new javax.swing.GroupLayout(pnlCharacter);
        pnlCharacter.setLayout(pnlCharacterLayout);
        pnlCharacterLayout.setHorizontalGroup(
            pnlCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCharacterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCharacterLayout.createSequentialGroup()
                        .addGroup(pnlCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGladName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCharacterLayout.setVerticalGroup(
            pnlCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCharacterLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblGladName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Save");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Open");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("New");
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Exit...");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem5.setText("About");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Help");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0)
                .addComponent(pnlCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pnlCharacter, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       JOptionPane.showMessageDialog(null, "r u a n0b?");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void cmbSwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSwordActionPerformed
        switch(cmbSword.getSelectedIndex()){
            case 1: 
                lblSword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frostmourne.PNG")));
            break;
            default:
                lblSword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basicsword.png")));
            break;
        }
    }//GEN-LAST:event_cmbSwordActionPerformed

    private void cmbSpearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSpearActionPerformed
        switch(cmbSpear.getSelectedIndex()){
            case 1: 
                lblSpear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elitespear.png")));
            break;
            default:
                lblSpear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spear.PNG")));
            break;
        }
    }//GEN-LAST:event_cmbSpearActionPerformed

    private void cmbMaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMaceActionPerformed
        switch(cmbMace.getSelectedIndex()){
            case 1: 
                lblMace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sulfuras.png")));
            break;
            default:
                lblMace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TwoHandedMaceBasic.PNG")));
            break;
        }
    }//GEN-LAST:event_cmbMaceActionPerformed

    private void cmbAxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAxeActionPerformed
        switch(cmbAxe.getSelectedIndex()){
            case 1: 
                lblAxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2heliteaxe.PNG")));
            break;
            default:
                lblAxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gimli.png")));
            break;
        }
    }//GEN-LAST:event_cmbAxeActionPerformed

    private void cmb1hMaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1hMaceActionPerformed
        switch(cmb1hMace.getSelectedIndex()){
            case 1: 
                lbl1hMace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/angmar.png")));
            break;
            default:
                lbl1hMace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OnehandedMaceBasic.PNG")));
            break;
        }
    }//GEN-LAST:event_cmb1hMaceActionPerformed

    private void cmbDaggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDaggerActionPerformed
        switch(cmbDagger.getSelectedIndex()){
            case 1: 
                lblDagger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elitedagger.png")));
            break;
            default:
                lblDagger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basicDagger.png")));
            break;
        }
    }//GEN-LAST:event_cmbDaggerActionPerformed

    private void cmbShieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbShieldActionPerformed
        switch(cmbShield.getSelectedIndex()){
            case 1: 
                lblShield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/romersk.png")));
            break;
            default:
                lblShield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rundsköld.png")));
            break;
        }
    }//GEN-LAST:event_cmbShieldActionPerformed

    private void btnBuy2hMaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuy2hMaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuy2hMaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy1hMace;
    private javax.swing.JButton btnBuy2hMace;
    private javax.swing.JButton btnBuyAxe;
    private javax.swing.JButton btnBuyDagger;
    private javax.swing.JButton btnBuyShield;
    private javax.swing.JButton btnBuySpear;
    private javax.swing.JButton btnBuySword;
    private javax.swing.JButton btnCloth;
    private javax.swing.JButton btnLeather;
    private javax.swing.JButton btnMetal;
    private javax.swing.JButton btnRing;
    private javax.swing.JComboBox cmb1hMace;
    private javax.swing.JComboBox cmbAxe;
    private javax.swing.JComboBox cmbCloth;
    private javax.swing.JComboBox cmbDagger;
    private javax.swing.JComboBox cmbLeather;
    private javax.swing.JComboBox cmbMace;
    private javax.swing.JComboBox cmbMetal;
    private javax.swing.JComboBox cmbRing;
    private javax.swing.JComboBox cmbShield;
    private javax.swing.JComboBox cmbSpear;
    private javax.swing.JComboBox cmbSword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbl1hMace;
    private javax.swing.JLabel lblAxe;
    private javax.swing.JLabel lblDagger;
    private javax.swing.JLabel lblExp;
    private javax.swing.JLabel lblGladName;
    private javax.swing.JLabel lblGold;
    private javax.swing.JLabel lblHp;
    private javax.swing.JLabel lblLeather;
    private javax.swing.JLabel lblLvl;
    private javax.swing.JLabel lblMace;
    private javax.swing.JLabel lblMetal;
    private javax.swing.JLabel lblRings;
    private javax.swing.JLabel lblShield;
    private javax.swing.JLabel lblSpear;
    private javax.swing.JLabel lblSword;
    private javax.swing.JPanel pnl1handedMarket;
    private javax.swing.JPanel pnl2HandedMarket;
    private javax.swing.JPanel pnlArena;
    private javax.swing.JPanel pnlArmorMarket;
    private javax.swing.JPanel pnlCharacter;
    private javax.swing.JPanel pnlHero;
    private javax.swing.JPanel pnlMarketplace;
    private javax.swing.JPanel pnlShieldMarket;
    private javax.swing.JTabbedPane tabMarket;
    private javax.swing.JTextField txfExp;
    private javax.swing.JTextField txfGold;
    private javax.swing.JTextField txfHp;
    private javax.swing.JTextField txfLvl;
    // End of variables declaration//GEN-END:variables
}
